### ISSUE TITLE
caffe训练以及前向推理

### ISSUE THREAD

**Issue by shutdownup** [imistyrain/RepVGG-caffe#1]
请问在caffe下训练后，怎样将训练保存的caffemodel转换到前向推理所使用的caffemodel。

**Comment by imistyrain** [comment]
和pytorch似的合并下权重就好

**Comment by wanyne-yyds** [comment]
可以提供一下合并工具？

**Comment by 0-LL-0** [comment]
请问：是如何从pytorch权重得到你release的caffe权重？

**Comment by imistyrain** [comment]
自己写的工具

**Comment by 0-LL-0** [comment]
> 自己写的工具

OK, Thanks.

**Comment by 0-LL-0** [comment]
@imistyrain 你好，我运行demo.py脚本，测试RepVGG-A0.caffemodel模型，结果和您一致。
![image](https://user-images.githubusercontent.com/12853603/105807386-d96c5280-5fe0-11eb-8306-34ee8e01ec2f.png)

当测试RepVGG-A0-train.caffemodel，结果不相同了。两者的结果不应该完全相同吗？【我把pooling层的ceild注释掉了】。
![image](https://user-images.githubusercontent.com/12853603/105807347-c35e9200-5fe0-11eb-96b6-e52d714421eb.png)

**Comment by imistyrain** [comment]
train后面没加softmax， 加上就一样了

**Comment by 0-LL-0** [comment]
> train后面没加softmax， 加上就一样了

是的，发现了，经过验证，完全一致。感谢您的回复。

**Comment by 0-LL-0** [comment]
@shutdownup @chenkangning 我写了一个，你们试试看。[merge](https://github.com/Li-Lai/RepVGG-caffe)

**Comment by wanyne-yyds** [comment]
> @shutdownup @chenkangning我写了一个，你们试试看。[合并](https://github.com/Li-Lai/RepVGG-caffe)

谢谢！

**Comment by shutdownup** [comment]
> @shutdownup @chenkangning 我写了一个，你们试试看。[merge](https://github.com/Li-Lai/RepVGG-caffe)

非常感谢。

**Comment by chgit0214** [comment]
onnx2caffe脚本能提供一下吗
